# Change these first
owner: RS-PYTHON
repo: upptime # The name of this repository

sites:
  - name: rs-server-auxip
    url: https://rspy.ops.rs-python.eu/auxip
    headers:
      - "x-api-key: $RS_SERVER_API_KEY"
    icon: https://avatars.githubusercontent.com/u/147415456?s=48&v=4
  - name: rs-server-cadip
    url: https://rspy.ops.rs-python.eu/cadip
    headers:
      - "x-api-key: $RS_SERVER_API_KEY"
    icon: https://avatars.githubusercontent.com/u/147415456?s=48&v=4
  - name: rs-server-catalog
    url: https://rspy.ops.rs-python.eu/catalog
    headers:
      - "x-api-key: $RS_SERVER_API_KEY"
    icon: https://avatars.githubusercontent.com/u/147415456?s=48&v=4
  - name: rs-server-frontend
    url: https://rspy.ops.rs-python.eu/docs
    icon: https://avatars.githubusercontent.com/u/147415456?s=48&v=4
  - name: rs-server-staging
    url: https://rspy.ops.rs-python.eu/processes
    headers:
      - "x-api-key: $RS_SERVER_API_KEY"
    icon: https://avatars.githubusercontent.com/u/147415456?s=48&v=4
  - name: stac-browser-cadip
    url: https://stac-browser-cadip.ops.rs-python.eu
    icon: https://avatars.githubusercontent.com/u/25801078?s=48&v=4
  - name: stac-browser-auxip
    url: https://stac-browser-auxip.ops.rs-python.eu
    icon: https://avatars.githubusercontent.com/u/25801078?s=48&v=4
  - name: stac-browser-catalog
    url: https://stac-browser-catalog.ops.rs-python.eu
    icon: https://avatars.githubusercontent.com/u/25801078?s=48&v=4
  - name: prefect
    url: https://processing.ops.rs-python.eu
    icon: https://avatars.githubusercontent.com/u/39270919?s=48&v=4
  - name: jupyter
    url: https://processing.ops.rs-python.eu/jupyter
    icon: https://avatars.githubusercontent.com/u/17927519?s=200&v=4
  - name: keycloak
    url: https://iam.ops.rs-python.eu
  - name: api-key-manager
    url: https://apikeymanager.ops.rs-python.eu/docs
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Green_icon_-_Key.ZGH.png/250px-Green_icon_-_Key.ZGH.png
  - name: grafana
    url: https://monitoring.ops.rs-python.eu
    icon: https://avatars.githubusercontent.com/u/7195757?s=200&v=4
  - name: prometheus
    url: https://monitoring.ops.rs-python.eu/prometheus
    icon: https://avatars.githubusercontent.com/u/3380462?s=200&v=4
  - name: neuvector
    url: $NEUVECTOR_URL
    icon: https://avatars.githubusercontent.com/u/19367275?s=48&v=4
  - name: wazuh
    url: $WAZUH_URL
    icon: https://avatars.githubusercontent.com/u/13752566?s=200&v=4
  - name: website
    url: https://home.rs-python.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: home.rs-python.eu
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/RS-PYTHON/RS-PYTHON.github.io/refs/heads/main/assets/logo/logo.jpg 
  name: Copernicus Reference System Python System Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RS-PYTHON/upptime).
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
